version: '3.8'
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000 # Adjust according to your host's user ID
      - PGID=1000 # Adjust according to your host's group ID
      - TZ=America/Los_Angeles
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - type: bind
        source: /mnt/d/Downloads/deluge/config
        target: /config
      - type: bind
        source: /mnt/d/Downloads/deluge/downloads
        target: /downloads
      - type: bind
        source: /mnt/d/Downloads/deluge/logs
        target: /config/logs
    ports:
      - 8120:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8192M
        reservations:
          cpus: '0.5'
          memory: 1024M
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8112 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 5m
