version: '3.8'
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000 # Adjust according to your host's user ID
      - PGID=1000 # Adjust according to your host's group ID
      - TZ=America/Los_Angeles
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - type: bind
        source: /d/Downloads/deluge/config
        target: /config
      - type: bind
        source: /d/Downloads/deluge/downloads
        target: /downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1024M
